### ISSUE TITLE
Publish chill-core as a npm package

### ISSUE THREAD

**Issue by mesaugat** [leapfrogtechnology/chill-core#1]
Currently, every other repository that uses `chill-core` has to build chill-core from itself.

**Comment by mesaugat** [comment]
@leapfrogtechnology/the-chill-team Should I publish the `master` branch as `v1.0.0-beta.1`?

**Comment by romitamgai** [comment]
> @leapfrogtechnology/the-chill-team Should I publish the `master` branch as `v1.0.0-beta.1`?

All the other chill repositories with `v1.0.0-beta.1` don't use this package. If we don't want to align the tags then we can release it.

**Comment by kabirbaidhya** [comment]
We need to align tags across all repos. If they don't use it now, let's not tag on the core; on the subsequent releases, we can.
